# BPP-specific values for onix-rabbitmq
component: bpp

image:
  repository: manendrapalsingh/onix-bpp-plugin-rabbit-mq
  tag: latest

service:
  port: 8002
  targetPort: 8002

redis:
  enabled: true
  service:
    port: 6379

env:
  - name: CONFIG_FILE
    value: /app/config/message-baised/rabbit-mq/onix-bpp/adapter.yaml
  - name: RABBITMQ_USERNAME
    value: admin
  - name: RABBITMQ_PASSWORD
    value: admin

