# BAP-specific values for onix-rabbitmq
component: bap

image:
  repository: manendrapalsingh/onix-bap-plugin-rabbit-mq
  tag: latest

service:
  port: 8001
  targetPort: 8001

redis:
  enabled: true
  service:
    port: 6379

env:
  - name: CONFIG_FILE
    value: /app/config/message-baised/rabbit-mq/onix-bap/adapter.yaml
  - name: RABBITMQ_USERNAME
    value: admin
  - name: RABBITMQ_PASSWORD
    value: admin

